#pragma once

enum LConst
{
	L_COLOR_WHITE = 1,
	L_COLOR_BLACK = 2,
	L_COLOR_ANY = 4,

	L_TYPE_BI,
	L_TYPE_BOT,
	L_TYPE_NET,

	L_FIGURE_KING,
	L_FIGURE_QUEEN,
	L_FIGURE_ELEPHANT,
	L_FIGURE_HORSE,
	L_FIGURE_ROOK,
	L_FIGURE_PAWN,

	L_SQUARE_NATIVE,
	L_SQUARE_FOCUSED,
	L_SQUARE_SELECTED,
	L_SQUARE_VARIANT,
	L_SQUARE_VARIANT_FOCUSED,

	L_PATH_FALSE = 0,
	L_PATH_TRUE = 1,
	L_PATH_CASTLING = 2,
	L_PATH_TRANSFORMATION = 4,
	L_PATH_CHECK = 8,
	L_PATH_MAT = 16,
	L_PATH_PAT = 32,

	L_CHESS_BOARD_SIZE = 8,
	L_FIGURE_COUNT = 32,
	L_SQUARE_COUNT = 64,

	L_PADDING_BOARD = 30,
	L_WIDTH_MENU = 150,
	L_WIDTH_CHESS = 1130,
	L_HEIGHT = 720
};
